source 'https://rubygems.org'

ruby '3.0.2'

gem 'bcrypt-ruby'
gem 'data_mapper'
gem 'pg'
gem 'rack-flash3'
gem 'sinatra'
gem 'sinatra-partial'
gem 'capybara'
gem 'database_cleaner'
gem 'rspec'
gem 'rspec-sinatra'
gem 'rubocop'
gem 'rubocop-rspec'